services:

  kong:
    ports: !override
      - ${KONG_HTTP_PORT}:8000/tcp

  mail:
    container_name: supabase-mail
    image: inbucket/inbucket:3.0.3
    restart: unless-stopped
    ports:
      - ${LOCAL_SMTP_PORT}:9000 # web interface
    volumes:
      - mail-storage:/storage

  # Database backup
  backup:
    container_name: supabase-backup
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    user: postgres:postgres
    volumes:
      - ${BACKUP_VOLUME}:/backups
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${BACKUP_TZ}
      - SCHEDULE=0 45 * * * *
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_MINS=1440
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=12

volumes:
  mail-storage: